spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/habitdb
    #url: jdbc:postgresql://host.docker.internal:5432/habitdb
    username: habit
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379

jwt:
  secret: "QkFTRTY0X1NUUklOR19GUk9NX0FCT1ZF"
  expiration-ms: 32000
server:
  port: 8082